FROM python:3.10

WORKDIR /code

COPY ./app /code/app
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


CMD ["uvicorn", "servicios:app", "--host", "0.0.0.0", "--port", "80", "--reload"]